export const FETCH_ALL_FLIGHTS = 'FETCH_ALL_FLIGHTS';
export const FLIGHTS_FETCH_SUCCEEDED = 'FLIGHTS_FETCH_SUCCEEDED';
export const FLIGHTS_FETCH_FAILED = 'FLIGHTS_FETCH_FAILED';
export const FETCH_ONE_FLIGHT = 'FETCH_ONE_FLIGHT';
export const ONE_FLIGHT_FETCH_SUCCEEDED = 'ONE_FLIGHT_FETCH_SUCCEEDED';
export const ONE_FLIGHT_FETCH_FAILED = 'ONE_FLIGHT_FETCH_FAILED';